#!/usr/bin/env bash
# Post-provision hook – writes src/GovernanceCouncil.Web/.env from AZD outputs

set -euo pipefail

echo ""
echo "=== Post-provision: writing .env ==="

# AZD runs hooks from the azure.yaml directory (Governance-Council/)
PROJECT_DIR="$(pwd)"
echo "  Project directory: $PROJECT_DIR"

ENV_DIR="${PROJECT_DIR}/src/GovernanceCouncil.Web"
mkdir -p "$ENV_DIR"

ENV_FILE="${ENV_DIR}/.env"
TEMPLATE="${ENV_DIR}/.env.template"
if [ ! -f "$TEMPLATE" ]; then
  echo "  ERROR: template not found: $TEMPLATE" >&2
  exit 1
fi

# Default the tenant from the signed-in account if azd didn't surface it.
: "${AZURE_TENANT_ID:=$(az account show --query tenantId -o tsv)}"

# Generate .env from .env.template: expand ${VAR} and ${VAR:-default} from the environment.
# Comment (#...) and blank lines pass through verbatim; only KEY=value lines are expanded.
# No eval / command substitution — safe indirect expansion only.
{
  echo "# Auto-generated by azd postprovision from .env.template - $(date '+%Y-%m-%d %H:%M:%S')"
  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      '#'*|'')
        printf '%s\n' "$line"
        ;;
      *)
        out=""
        rest="$line"
        while [[ "$rest" =~ \$\{([A-Za-z_][A-Za-z0-9_]*)(:-([^}]*))?\} ]]; do
          full="${BASH_REMATCH[0]}"
          name="${BASH_REMATCH[1]}"
          def="${BASH_REMATCH[3]}"
          out="${out}${rest%%"$full"*}"
          val="${!name:-}"
          [ -z "$val" ] && val="$def"
          out="${out}${val}"
          rest="${rest#*"$full"}"
        done
        printf '%s\n' "${out}${rest}"
        ;;
    esac
  done < "$TEMPLATE"
} > "$ENV_FILE"

echo "  Written to: $ENV_FILE"
echo ""

# Trust the ASP.NET Core HTTPS development certificate (idempotent; no-op if already trusted).
# On Linux this prints a notice (manual trust may be needed); on macOS it adds it to the keychain.
echo "=== Trusting ASP.NET Core HTTPS dev certificate ==="
dotnet dev-certs https --trust || true

echo ""
echo "=== Next steps ==="
echo "  1. cd src/GovernanceCouncil.Web && dotnet run"
echo "  2. Open https://localhost:7080"
echo ""
