#!/usr/bin/env pwsh
# Post-provision hook – writes src/GovernanceCouncil.Web/.env from AZD outputs

Write-Host "`n=== Post-provision: writing .env ===" -ForegroundColor Cyan

# AZD runs hooks from the azure.yaml directory (Governance-Council/)
# Use the current working directory, not $env:AZD_PROJECT_DIR which may not be set
$projectDir = Get-Location
Write-Host "  Project directory: $projectDir"

$envDir = Join-Path $projectDir "src" "GovernanceCouncil.Web"
if (-not (Test-Path $envDir)) {
    New-Item -ItemType Directory -Path $envDir -Force | Out-Null
}

$envFile = Join-Path $envDir ".env"
$template = Join-Path $envDir ".env.template"
if (-not (Test-Path $template)) {
    throw "Template not found: $template"
}

# Default the tenant from the signed-in account if azd didn't surface it.
if (-not $env:AZURE_TENANT_ID) {
    $env:AZURE_TENANT_ID = (az account show --query tenantId -o tsv)
}

# Generate .env from .env.template: expand ${VAR} and ${VAR:-default} from the environment.
# Comment (#...) and blank lines pass through verbatim; only KEY=value lines are expanded.
$pattern = '\$\{([A-Za-z_][A-Za-z0-9_]*)(?::-([^}]*))?\}'
$expanded = foreach ($line in (Get-Content -Path $template)) {
    if ($line -match '^\s*#' -or $line.Trim() -eq '') {
        $line
    }
    else {
        [regex]::Replace($line, $pattern, {
            param($m)
            $val = [Environment]::GetEnvironmentVariable($m.Groups[1].Value)
            if ([string]::IsNullOrEmpty($val)) { $m.Groups[2].Value } else { $val }
        })
    }
}

$header = "# Auto-generated by azd postprovision from .env.template - $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
Set-Content -Path $envFile -Value (@($header) + $expanded) -Encoding utf8NoBOM

Write-Host "  Written to: $envFile" -ForegroundColor Green
Write-Host ""

# Trust the ASP.NET Core HTTPS development certificate so https://localhost runs without browser
# warnings. Idempotent (no-op if already trusted); may show a one-time OS confirmation on first run.
Write-Host "=== Trusting ASP.NET Core HTTPS dev certificate ===" -ForegroundColor Cyan
dotnet dev-certs https --trust

Write-Host ""
Write-Host "=== Next steps ===" -ForegroundColor Yellow
Write-Host "  1. cd src/GovernanceCouncil.Web && dotnet run"
Write-Host "  2. Open https://localhost:7080"
Write-Host ""
